"""
    Core

General-`k` Josephus function and the extremal-point machinery of

    [1] Bello-Cruz & Quintero-Contreras, Analytical Study and Efficient Evaluation
        of the Josephus Function, J. Integer Seq. 27 (2024), Article 24.3.8.

Positions are numbered `1, 2, ..., n` around the circle, and every `k`-th person is
eliminated until one survivor remains. `J_k(n)` is the survivor's starting position.
"""
module JosephusCore

export josephus, josephus_euler, josephus_knuth,
       next_high_extremal, high_extremal_points, josephus_extremal,
       fixed_points, fixed_points_bruteforce, is_fixed_point

# ----------------------------------------------------------------------
# Naive / reference implementations
# ----------------------------------------------------------------------

"""
    josephus_euler(k, n)

Survivor position `J_k(n)` via Euler's order-`n` recurrence
`J_k(1) = 1`, `J_k(i) = ((J_k(i-1) + k - 1) mod i) + 1`.

This is the reference implementation: O(n) time, exact, used to validate the fast
methods. Cf. [1, Sec. 5, Euler's algorithm].
"""
function josephus_euler(k::Integer, n::Integer)
    k >= 2 || throw(ArgumentError("step size k must be >= 2"))
    n >= 1 || throw(ArgumentError("n must be >= 1"))
    r = 0                      # 0-based survivor index
    @inbounds for i in 2:n
        r = (r + k) % i
    end
    return r + 1               # back to 1-based
end

"""
    josephus_knuth(k, n)

Survivor position `J_k(n)` via Knuth's O(k log n) method
(Graham–Knuth–Patashnik, eq. (3.19)), included as an independent cross-check.
Cf. [1, Sec. 5, Knuth's algorithm].
"""
function josephus_knuth(k::Integer, n::Integer)
    k >= 2 || throw(ArgumentError("step size k must be >= 2"))
    n >= 1 || throw(ArgumentError("n must be >= 1"))
    # Knuth's jumping method (Concrete Mathematics, Sec. 3.3): iterate
    # D <- ceil(k*D/(k-1)) while D <= (k-1)*n, then J_k(n) = k*n + 1 - D.
    D = 1
    while D <= (k - 1) * n
        D = div(k * D + k - 2, k - 1)        # ceil(k*D/(k-1))
    end
    return k * n + 1 - D
end

"""
    josephus(k, n)

Survivor position `J_k(n)`. For modest `n` this calls the exact Euler recurrence;
for large `n` consider [`josephus_extremal`](@ref) (general k) or the specialized
`josephus4_evaluate` (k = 4).
"""
josephus(k::Integer, n::Integer) = josephus_euler(k, n)

# ----------------------------------------------------------------------
# Extremal-point structure (paper [1])
# ----------------------------------------------------------------------
#
# A high extremal point n_e satisfies J_k(n_e) in [[n_e-k+2, n_e]]; it is a fixed
# point when J_k(n_e) = n_e. Between consecutive high extremal points J_k is linear
# of slope k. Corollary "L 3" of [1] gives the next high extremal point and its
# value from the current one, which is the engine of the extremal evaluation.

"""
    next_high_extremal(k, ne, jne) -> (ne_next, j_next)

Given a high extremal point `ne >= 2k-3` of `J_k` with value `jne = J_k(ne)`,
return the next high extremal point `ne_next` and its value `J_k(ne_next)`.

Implements the recurrence of [1, Corollary "L 3"]:
with `j = (k-1) - (ne - jne)` the value just after `ne`, `r = ne mod (k-1)`, and
`c = 1` if `r < k-2-ne+jne` else `0`,
`ne_next = (k*(ne+1) - (r+1)) / (k-1) - c`.
"""
function next_high_extremal(k::Integer, ne::Integer, jne::Integer)
    k >= 2 || throw(ArgumentError("step size k must be >= 2"))
    km1 = k - 1
    # value of J_k at ne+1 (Theorem "L 2-part2"(c) of [1])
    jafter = km1 - (ne - jne)
    r = mod(ne, km1)
    c = r < (k - 2 - ne + jne) ? 1 : 0
    ne_next = div(k * (ne + 1) - (r + 1), km1) - c
    # value at the next high extremal point, eq. (jk-nei+1) of [1]
    j_next = km1 - ne + jne + k * fld(2 * ne - jne - (k - 2), km1)
    return ne_next, j_next
end

"""
    _first_high_extremal(k) -> (ne1, j1)

The first high extremal point `>= 2k-3` and its value, used to seed the walk.
Cf. the initialization in [1, Sec. 5, Extremal algorithm].
"""
function _first_high_extremal(k::Integer)
    j = josephus_euler(k, 2k - 2)               # J_k(2k-2)
    if j <= k - 1
        return (2k - 3, j + k - 2)
    else
        return (2k - 2, j)
    end
end

"""
    high_extremal_points(k, N) -> Vector{Tuple{Int,Int}}

All high extremal points `ne <= N` of `J_k`, returned as `(ne, J_k(ne))` pairs in
increasing order, generated by iterating [`next_high_extremal`](@ref). No
intermediate values of `J_k` are computed.
"""
function high_extremal_points(k::Integer, N::Integer)
    out = Tuple{Int,Int}[]
    ne, j = _first_high_extremal(k)
    while ne <= N
        push!(out, (ne, j))
        ne, j = next_high_extremal(k, ne, j)
    end
    return out
end

"""
    josephus_extremal(k, n) -> Int

Survivor position `J_k(n)` via the extremal algorithm of [1]: walk the high extremal
points of `J_k` until one passes `n`, then read off `J_k(n)` from the linear segment
of slope `k` that contains `n`. Uses O(log n) steps instead of the O(n) recurrence.

For small `n` (`n < 2k-3`, before the regular structure begins) this falls back to
the exact Euler recurrence.
"""
function josephus_extremal(k::Integer, n::Integer)
    k >= 2 || throw(ArgumentError("step size k must be >= 2"))
    n >= 1 || throw(ArgumentError("n must be >= 1"))
    n < 2k - 3 && return josephus_euler(k, n)

    ne, j = _first_high_extremal(k)
    if n <= ne
        return josephus_euler(k, n)
    end
    # advance until the segment (ne, ne_next] contains n
    while true
        ne_next, j_next = next_high_extremal(k, ne, j)
        if n <= ne_next
            # J_k linear of slope k on [[ne+1, ne_next]], anchored at the right end:
            # J_k(n) = J_k(ne_next) + k*(n - ne_next)   (eq. (jk-n) of [1])
            return j_next + k * (n - ne_next)
        end
        ne, j = ne_next, j_next
    end
end

# ----------------------------------------------------------------------
# Fixed points for general k
# ----------------------------------------------------------------------

"""
    is_fixed_point(k, n) -> Bool

True iff `J_k(n) = n` (uses the exact Euler recurrence).
"""
is_fixed_point(k::Integer, n::Integer) = josephus_euler(k, n) == n

"""
    fixed_points_bruteforce(k, N) -> Vector{Int}

All fixed points `n <= N` of `J_k`, found by scanning with the exact recurrence.
O(N) total. Reference implementation used to validate the fast generators.
"""
function fixed_points_bruteforce(k::Integer, N::Integer)
    k >= 2 || throw(ArgumentError("step size k must be >= 2"))
    out = Int[]
    r = 0
    @inbounds for i in 1:N
        i == 1 ? (r = 0) : (r = (r + k) % i)
        if r + 1 == i
            push!(out, i)
        end
    end
    return out
end

"""
    fixed_points(k, m) -> Vector{Int}

The first `m` fixed points of `J_k`, generated by walking high extremal points with
[`next_high_extremal`](@ref) and collecting those that land on the diagonal
(`J_k(ne) = ne`). This avoids scanning every integer.

For `k = 2` the closed form `2^i - 1` is used directly; for `k = 3` and `k = 4`,
faster specialized recurrences are available as [`fixed_points_J3`](@ref) and
[`fixed_points_J4`](@ref).
"""
function fixed_points(k::Integer, m::Integer)
    k >= 2 || throw(ArgumentError("step size k must be >= 2"))
    m >= 0 || throw(ArgumentError("m must be >= 0"))
    m == 0 && return Int[]

    if k == 2
        return [2^i - 1 for i in 1:m]            # Knuth's closed form
    end

    out = Int[]
    # Fixed points below the threshold 2k-3 (where the extremal recurrence begins)
    # must be found directly; the walk below would skip them.
    r = 0
    @inbounds for i in 1:(2k - 4)
        i == 1 ? (r = 0) : (r = (r + k) % i)
        if r + 1 == i
            push!(out, i)
            length(out) >= m && return out[1:m]
        end
    end
    # Walk the high extremal points >= 2k-3 and collect those on the diagonal.
    ne, j = _first_high_extremal(k)
    while length(out) < m
        if ne == j && (isempty(out) || out[end] != ne)
            push!(out, ne)
            length(out) >= m && break
        end
        ne, j = next_high_extremal(k, ne, j)
    end
    return out[1:m]
end

end # module JosephusCore
