"""
    J3

Fixed points of the Josephus function `J_3`, implementing

    [2] Bello-Cruz & Quintero-Contreras, On the Recurrence Formula for Fixed Points
        of the Josephus Function, Integers 24 (2024), #A115.
    [3] Bello-Cruz & Quintero-Contreras, Fixed Points of the Josephus Function via
        Fractional Base Expansions, Integers 26 (2026), #A54.

The fixed-point sequence of `J_3` starts `1, 2, 13, 20, 46, 157, 236, ...`.
"""
module J3

export fixed_points_J3, fixed_points_J3_recurrence, num_pure_points_J3,
       josephus3_via_fixed_points, fixed_point_J3_crt, base_three_halves

"""
    _val2(m) -> Int

2-adic valuation: the largest `t >= 0` with `2^t | m` (with `_val2(0) = typemax`).
"""
function _val2(m::Integer)
    m == 0 && return typemax(Int)
    t = 0
    while iseven(m)
        m >>= 1
        t += 1
    end
    return t
end

"""
    num_pure_points_J3(np) -> Int

Number of pure high extremal points between the fixed point `np = n_p^{(ℓ)}` and the
next fixed point of `J_3`. By [2, Theorem "Recurrence Formula"], this equals
`ν_2(3*np + 2)`, the 2-adic valuation of `3*np + 2`.
"""
num_pure_points_J3(np::Integer) = _val2(3 * np + 2)

"""
    fixed_points_J3_recurrence(np) -> Int

Given a fixed point `np = n_p^{(ℓ)}` of `J_3`, return the next fixed point
`n_p^{(ℓ+1)}` via the closed recurrence of [2, Theorem "Recurrence Formula"]:
with `m = ν_2(3*np + 2)`,

    n_p^{(ℓ+1)} = (3^m (3*np + 2) - 2^m) / 2^{m+1}.
"""
function fixed_points_J3_recurrence(np::Integer)
    m = num_pure_points_J3(np)
    return Int(div(big(3)^m * (3 * np + 2) - big(2)^m, big(2)^(m + 1)))
end

"""
    fixed_points_J3(m) -> Vector{Int}

The first `m` fixed points of `J_3`, generated by iterating the recurrence of [2]
from `n_p^{(1)} = 1`. Far faster than scanning: each step is a 2-adic valuation and a
handful of big-integer operations.

```jldoctest
julia> fixed_points_J3(7)
7-element Vector{Int64}:
   1
   2
  13
  20
  46
 157
 236
```
"""
function fixed_points_J3(m::Integer)
    m >= 0 || throw(ArgumentError("m must be >= 0"))
    m == 0 && return Int[]
    out = Vector{Int}(undef, m)
    out[1] = 1
    np = 1
    for i in 2:m
        np = fixed_points_J3_recurrence(np)
        out[i] = np
    end
    return out
end

"""
    josephus3_via_fixed_points(n) -> Int

Evaluate `J_3(n)` using only the fixed-point sequence, following the closed formula
of [2]. Locates the fixed-point interval containing `n`, then reads `J_3(n)` from the
relevant linear segment. Returns the same value as the direct recurrence.

The implementation generates fixed points until it brackets `n`, so it touches only
`O(log n)` fixed points rather than all `n` predecessors.
"""
function josephus3_via_fixed_points(n::Integer)
    n >= 1 || throw(ArgumentError("n must be >= 1"))
    n == 1 && return 1
    # bracket n by consecutive fixed points np_l <= n < np_{l+1}
    npl = 1
    npl1 = fixed_points_J3_recurrence(npl)
    while npl1 <= n
        npl = npl1
        npl1 = fixed_points_J3_recurrence(npl)
    end
    n == npl && return n                       # n is itself a fixed point
    # Within (npl, npl1], J_3 climbs in slope-3 segments separated by the
    # mbar = ν_2(3 npl + 2) pure points. Reconstruct J_3(n) from the segment.
    mbar = num_pure_points_J3(npl)
    # pure high extremal points in the interval (see [2, eqs. (n-e-ell-1), (n-e-ell-j)])
    # n_e^{(ℓ_1)} = 3 npl / 2 ; n_e^{(ℓ_j)} = 3^{j-1}(3 npl + 2)/2^j - 1, j>=2.
    seg_start = npl                            # left endpoint of current segment - 1
    seg_val0 = npl                             # J_3 at seg_start
    pures = Int[]
    if mbar >= 1
        push!(pures, div(3 * npl, 2))
        for j in 2:mbar
            push!(pures, Int(div(big(3)^(j - 1) * (3 * npl + 2), big(2)^j)) - 1)
        end
    end
    # endpoints of the linear pieces: npl, pures..., npl1
    lefts = vcat([npl], pures)
    rights = vcat(pures, [npl1])
    for (a, b) in zip(lefts, rights)
        if a < n <= b
            # On (a, b], J_3 is linear of slope 3 ending at J_3(b).
            # J_3(b) = b if b is a fixed point (b == npl1), else b - 1 (pure point).
            jb = (b == npl1) ? b : b - 1
            return jb - 3 * (b - n)
        end
    end
    # Fallback (should not be reached): exact recurrence
    r = 0
    for i in 2:n
        r = (r + 3) % i
    end
    return r + 1
end

"""
    fixed_point_J3_crt(np_next, p, q) -> Bool

Check the Chinese-Remainder-Theorem characterization of [3]: a fixed point
`x = n_p^{(ℓ+1)}` of `J_3` satisfies

    2x + 1 ≡ 0 (mod 3^p)   and   3x + 2 ≡ 0 (mod 2^q),

where `p = ν_2(3 n_p^{(ℓ)} + 2)` is the number of pure points before `x` and
`q = ν_2(3x + 2)` the number after. Returns `true` iff both congruences hold.
"""
function fixed_point_J3_crt(np_next::Integer, p::Integer, q::Integer)
    c1 = mod(2 * np_next + 1, big(3)^p) == 0
    c2 = mod(3 * np_next + 2, big(2)^q) == 0
    return c1 && c2
end

"""
    base_three_halves(N) -> Vector{Int}

Represent `N >= 0` in the base-3/2 number system with digit set `{0, 1, 2}` studied
in [3], returned as digits `[d_k, ..., d_0]` (most significant first) with
`N = Σ d_i (3/2)^i`. Uses the Akiyama–Frougny–Sakarovitch recurrence
`d = N mod 3; N ← 2 (N - d) / 3`.

```jldoctest
julia> base_three_halves(13)
4-element Vector{Int64}:
 2
 1
 2
 1
```
"""
function base_three_halves(N::Integer)
    N >= 0 || throw(ArgumentError("N must be >= 0"))
    N == 0 && return [0]
    digits = Int[]
    x = N
    while x > 0
        d = mod(x, 3)
        push!(digits, d)
        x = 2 * div(x - d, 3)
    end
    return reverse(digits)
end

end # module J3
