"""
    J4

Fixed points of the Josephus function `J_4`, implementing

    [4] Bello-Cruz & Quintero-Contreras, A 3-adic Recurrence for the Fixed Points of
        the Josephus Function J_4, arXiv (2026).

The fixed-point sequence of `J_4` starts `1, 21, 38, 51, 122, 163, 689, 919, ...`.

The engine is the map `Φ` of [4, Lemma 4.1(b)]. A high extremal point `n_e` of type
`t ∈ {0, 1, 2}` (type 0 = fixed point) has value `j = J_4(n_e + 1) = 3 - t` just
after it (the type–value identity). With `ε = n_e mod 3` and
`δ = 1` if `ε < j - 1` else `0`,

    Φ(n_e)        = (4(n_e + 1) - (ε + 1)) ÷ 3 - δ,
    type(Φ(n_e))  = 3δ + ε - (j - 1).

A fixed point is reached exactly when the type is 0.
"""
module J4

export fixed_points_J4, next_fixed_point_J4, josephus4_evaluate,
       block_structure_J4, first_block_J4

"""
    _phi(ne, t) -> (ne_next, t_next)

The engine map `Φ` of [4, Lemma 4.1(b)]: from a high extremal point `ne` of type `t`,
return the next high extremal point and its type.
"""
function _phi(ne::Integer, t::Integer)
    j = 3 - t                       # J_4(ne+1), by the type-value identity
    eps = mod(ne, 3)
    delta = eps < j - 1 ? 1 : 0
    nxt = div(4 * (ne + 1) - (eps + 1), 3) - delta
    nxt_type = 3 * delta + eps - (j - 1)
    return nxt, nxt_type
end

"""
    next_fixed_point_J4(np) -> Int

The next fixed point of `J_4` after the fixed point `np`, obtained by walking high
extremal points with `Φ` until one lands on the diagonal (type 0). Implements the
recurrence of [4, Theorem 7.1].
"""
function next_fixed_point_J4(np::Integer)
    ne, t = np, 0
    while true
        ne, t = _phi(ne, t)
        t == 0 && return ne
    end
end

"""
    fixed_points_J4(m) -> Vector{Int}

The first `m` fixed points of `J_4`, from `n_p^{(1)} = 1`, via the recurrence of [4].
No intermediate values of `J_4` are computed.

```jldoctest
julia> fixed_points_J4(8)
8-element Vector{Int64}:
   1
  21
  38
  51
 122
 163
 689
 919
```
"""
function fixed_points_J4(m::Integer)
    m >= 0 || throw(ArgumentError("m must be >= 0"))
    m == 0 && return Int[]
    out = Vector{Int}(undef, m)
    out[1] = 1
    for i in 2:m
        out[i] = next_fixed_point_J4(out[i - 1])
    end
    return out
end

"""
    first_block_J4(np) -> (type, length, last_point)

The first block of pure high extremal points after the fixed point `np`, following
[4, Proposition 4.6]. The block type and length are read from the ternarity of `np`
and a single 3-adic valuation:

  * `np ≡ 2 (mod 3)`: direct transition, no pure points -> `(0, 0, np)`.
  * `np ≡ 0 (mod 3)`: first block of type 1, length `ν_3(4 np + 3)`.
  * `np ≡ 1 (mod 3)`: first block of type 2, length `ν_3(4 np + 2)`.

The formula applies to fixed points `np >= 3`; the initial fixed point `n_p^{(1)} = 1`
lies in the irregular region `n <= 6` excluded by [4, Theorem 7.1] and is not covered.
"""
function first_block_J4(np::Integer)
    np >= 3 || throw(ArgumentError(
        "first_block_J4 requires np >= 3; the fixed point 1 lies in the irregular " *
        "region n <= 6 excluded by the theorem"))
    tern = mod(np, 3)
    if tern == 2
        return (0, 0, np)                       # direct transition
    elseif tern == 0
        m1 = _val3(4 * np + 3)
        last = Int(div(big(4)^(m1 - 1) * (4 * np + 3), big(3)^m1)) - 1
        return (1, m1, last)
    else # tern == 1
        m2 = _val3(4 * np + 2)
        last = Int(div(big(4)^(m2 - 1) * (4 * np + 2), big(3)^m2)) - 1
        return (2, m2, last)
    end
end

"""
    _val3(m) -> Int

3-adic valuation: the largest `t >= 0` with `3^t | m`.
"""
function _val3(m::Integer)
    m == 0 && return typemax(Int)
    t = 0
    while mod(m, 3) == 0
        m = div(m, 3)
        t += 1
    end
    return t
end

"""
    block_structure_J4(np) -> Vector{Tuple{Int,Int,Int}}

The full block structure of the interval between the fixed point `np` and the next
fixed point of `J_4`, as a vector of `(type, length, last_point)` triples in order
(empty for a direct transition). Generated by walking `Φ` and grouping consecutive
pure points of equal type, per [4, Theorem 7.1].
"""
function block_structure_J4(np::Integer)
    blocks = Tuple{Int,Int,Int}[]
    ne, t = _phi(np, 0)
    cur_type = 0
    cur_len = 0
    cur_last = np
    while t != 0
        if t == cur_type
            cur_len += 1
            cur_last = ne
        else
            cur_type != 0 && push!(blocks, (cur_type, cur_len, cur_last))
            cur_type = t
            cur_len = 1
            cur_last = ne
        end
        ne, t = _phi(ne, t)
    end
    cur_type != 0 && push!(blocks, (cur_type, cur_len, cur_last))
    return blocks
end

"""
    josephus4_evaluate(n) -> Int

Evaluate `J_4(n)` at an arbitrary `n` using the fixed-point structure of [4,
Theorem 8.2]: locate the largest fixed point `<= n`, walk the high extremal points
of that interval with `Φ` until one passes `n`, and read `J_4(n)` off the slope-4
segment that contains it. Uses `O(#high extremal points in the interval)` steps,
independent of the size of `n`.

```jldoctest
julia> josephus4_evaluate(10000)
3254
```
"""
function josephus4_evaluate(n::Integer)
    n >= 1 || throw(ArgumentError("n must be >= 1"))
    n <= 6 && return _j4_small(n)               # initial irregular values
    # largest fixed point <= n
    np = 1
    nxt = next_fixed_point_J4(np)
    while nxt <= n
        np = nxt
        nxt = next_fixed_point_J4(np)
    end
    n == np && return n
    # walk high extremal points from np until one passes n
    e, t = np, 0
    while true
        e_next, t_next = _phi(e, t)
        if n <= e_next
            # J_4 is linear of slope 4 on (e, e_next], with value 3 - t_next at e_next
            j_at_enext = e_next - t_next
            return j_at_enext - 4 * (e_next - n)
        end
        e, t = e_next, t_next
    end
end

# the first six values J_4(1..6) = 1,1,2,2,1,5 (before the regular structure begins)
function _j4_small(n::Integer)
    small = (1, 1, 2, 2, 1, 5)
    return small[n]
end

end # module J4
